# Generated by Django 3.0.5 on 2020-05-03 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Aditional_details', models.TextField()),
                ('Zip', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(choices=[('ANI', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('ACP', 'Arunachal Pradesh'), ('AS', 'Assam'), ('B', 'Bihar'), ('CH', 'Chandigarh'), ('CHH', 'Chhattisgarh'), ('DNGH', 'Dadra and Nagar Haveli and Daman and Diu'), ('DL', 'National Capital Territory of Delhi'), ('G', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('J&K', 'Jammu and Kashmir'), ('JK', 'Jharkhand'), ('KN', 'Karnataka'), ('KL', 'Kerala'), ('LD', 'Ladakh'), ('LP', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('MG', 'Meghalaya'), ('MZ', 'Mizoram'), ('ND', 'Nagaland'), ('OD', 'Odisha'), ('PC', 'Puducherry'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TL', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')], max_length=20)),
                ('Sqft', models.IntegerField()),
                ('Lot_size', models.IntegerField()),
                ('Published_date', models.DateTimeField(default=datetime.datetime.now)),
                ('Bedrooms', models.IntegerField()),
                ('Bathrooms', models.IntegerField()),
                ('Garage', models.IntegerField(default=0)),
                ('Price', models.CharField(max_length=100)),
                ('Main_photo', models.ImageField(upload_to='image')),
                ('Optional_photos1', models.ImageField(blank=True, default='default.png', null=True, upload_to='image')),
                ('Optional_photos2', models.ImageField(blank=True, default='default.png', null=True, upload_to='image')),
                ('Optional_photos3', models.ImageField(blank=True, default='default.png', null=True, upload_to='image')),
                ('Optional_photos4', models.ImageField(blank=True, default='default.png', null=True, upload_to='image')),
                ('Optional_photos5', models.ImageField(blank=True, default='default.png', null=True, upload_to='image')),
                ('Optional_photos6', models.ImageField(blank=True, default='default.png', null=True, upload_to='image')),
                ('Age_of_Property', models.IntegerField()),
                ('Main_enterance_facing', models.CharField(max_length=50)),
                ('Realtor_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtors.Realtor')),
            ],
        ),
    ]
