# Generated by Django 3.0.5 on 2020-04-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Picture', models.ImageField(upload_to='image')),
                ('Mobile_No', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Experience', models.CharField(max_length=100)),
            ],
        ),
    ]
