State_choices={
		"ANI":'Andaman and Nicobar Islands',
		"AP":'Andhra Pradesh',
		"ACP":'Arunachal Pradesh',
		"AS":'Assam',
		"B":'Bihar',
		"CH":'Chandigarh',
		"CHH":'Chhattisgarh',
		"DNGH":'Dadra and Nagar Haveli and Daman and Diu',
		"DL":'National Capital Territory of Delhi',
		"G":'Goa',
		"GJ":'Gujarat',
		"HR":'Haryana',
		"HP":'Himachal Pradesh',
		"J&K":'Jammu and Kashmir',
		"JK":'Jharkhand',
		"KN":'Karnataka',
		"KL":'Kerala',
		"LD":'Ladakh',
		"LP":'Lakshadweep',
		"MP":'Madhya Pradesh',
		"MH":'Maharashtra',
		"MN":'Manipur',
		"MG":'Meghalaya',
		"MZ":'Mizoram',
		"ND":'Nagaland',
		"OD":'Odisha',
		"PC":'Puducherry',
		"PB":'Punjab',
		"RJ":'Rajasthan',
		"SK":'Sikkim',
		"TN":'Tamil Nadu',
		"TL":'Telangana',
		"TR":'Tripura',
		"UP":'Uttar Pradesh',
		"UK":'Uttarakhand',
		"WB":'West Bengal',
}

Bedroom_choices={
	"1":1,
	"2":2,
	"3":3,
	"4":4,
	"5":5,
	"6":6,
	"7":7,
	"8":8,
	"9":9,
	"10":10,
}

Price_choices={
	"1000000":'10L',
	"2000000":'20L',
	"3000000":'30L',
	"4000000":'40L',
	"5000000":'50L',
	"6000000":'60L',
	"7000000":'70L',
	"8000000":'80L',
	"9000000":'90L',
	"10000000":'1Cr',
}
STATE=(
		('ANI','Andaman and Nicobar Islands'),
		('AP','Andhra Pradesh'),
		('ACP','Arunachal Pradesh'),
		('AS','Assam'),
		('B','Bihar'),
		('CH','Chandigarh'),
		('CHH','Chhattisgarh'),
		('DNGH','Dadra and Nagar Haveli and Daman and Diu'),
		('DL','National Capital Territory of Delhi'),
		('G','Goa'),
		('GJ','Gujarat'),
		('HR','Haryana'),
		('HP','Himachal Pradesh'),
		('J&K','Jammu and Kashmir'),
		('JK','Jharkhand'),
		('KN','Karnataka'),
		('KL','Kerala'),
		('LD','Ladakh'),
		('LP','Lakshadweep'),
		('MP','Madhya Pradesh'),
		('MH','Maharashtra'),
		('MN','Manipur'),
		('MG','Meghalaya'),
		('MZ','Mizoram'),
		('ND','Nagaland'),
		('OD','Odisha'),
		('PC','Puducherry'),
		('PB','Punjab'),
		('RJ','Rajasthan'),
		('SK','Sikkim'),
		('TN','Tamil Nadu'),
		('TL','Telangana'),
		('TR','Tripura'),
		('UP','Uttar Pradesh'),
		('UK','Uttarakhand'),
		('WB','West Bengal'))